# -*- coding: utf-8 -*-
"""DS_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NVA8uscMxjzEG4FlRxJWmo6fuGlmGKpw
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("Placement_Data_Full_Class.csv")
df.head()

df.shape
df.info()
df.describe()

df.isnull().sum()

df.drop('salary', axis=1, inplace=True)

df.drop('sl_no', axis=1, inplace=True)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.select_dtypes(include='object'):
    df[col] = le.fit_transform(df[col])

sns.countplot(x='status', data=df)
plt.title("Placement Count")
plt.show()

plt.figure(figsize=(10,6))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.show()

from sklearn.model_selection import train_test_split

X = df.drop('status', axis=1)
y = df['status']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

lr_acc = lr.score(X_test, y_test)
print("Logistic Regression Accuracy:", lr_acc)

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

dt_acc = dt.score(X_test, y_test)
print("Decision Tree Accuracy:", dt_acc)

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X_train, y_train)

rf_acc = rf.score(X_test, y_test)
print("Random Forest Accuracy:", rf_acc)

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

knn_acc = knn.score(X_test, y_test)
print("KNN Accuracy:", knn_acc)

models = ['Logistic Regression', 'Decision Tree', 'Random Forest', 'KNN']
accuracy = [lr_acc, dt_acc, rf_acc, knn_acc]

plt.bar(models, accuracy)
plt.title("Model Comparison")
plt.show()