# -*- coding: utf-8 -*-
"""DS_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NVA8uscMxjzEG4FlRxJWmo6fuGlmGKpw
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import joblib

df = pd.read_csv("Placement_Data_Full_Class.csv")

df.drop(['salary', 'sl_no'], axis=1, inplace=True)

from sklearn.preprocessing import LabelEncoder

encoders = {}
for col in df.select_dtypes(include=['object', 'str']):
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le

# sns.countplot(x='status', data=df)
# plt.title("Placement Count")
# plt.show()

# plt.figure(figsize=(10,6))
# sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
# plt.show()

from sklearn.model_selection import train_test_split

X = df.drop('status', axis=1)
y = df['status']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

lr_acc = lr.score(X_test, y_test)
print(f"Logistic Regression Accuracy: {lr_acc:.4f}")

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

dt_acc = dt.score(X_test, y_test)
print(f"Decision Tree Accuracy: {dt_acc:.4f}")

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X_train, y_train)

rf_acc = rf.score(X_test, y_test)
print(f"Random Forest Accuracy: {rf_acc:.4f}")

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

knn_acc = knn.score(X_test, y_test)
print(f"KNN Accuracy: {knn_acc:.4f}")

# Save the best model (Logistic Regression often performs well here and is easy to port)
# Or save all needed for inference
model_data = {
    'model': lr,
    'encoders': encoders,
    'features': X.columns.tolist(),
    'accuracies': {
        'Logistic Regression': lr_acc,
        'Decision Tree': dt_acc,
        'Random Forest': rf_acc,
        'KNN': knn_acc
    }
}
joblib.dump(model_data, 'model_new.joblib')
print("Model and encoders saved to model_new.joblib")

def predict_placement(cgpa_10_scale):
    # Convert 0-10 scale to 0-100 percentage
    percentage = cgpa_10_scale * 10.0
    
    # Use default values for other features
    # These were calculated as means/modes of the training data
    input_data = {
        'gender': 1, # Male
        'ssc_p': 67.3,
        'ssc_b': 0, # Central
        'hsc_p': 66.3,
        'hsc_b': 1, # Others
        'hsc_s': 1, # Commerce
        'degree_p': percentage,
        'degree_t': 0, # Comm&Mgmt
        'workex': 0, # No
        'etest_p': 72.1,
        'specialisation': 0, # Mkt&Fin
        'mba_p': 62.3
    }
    
    # Create DataFrame for prediction
    input_df = pd.DataFrame([input_data])
    
    # Ensure feature order matches training
    input_df = input_df[X.columns]
    
    # Predict
    prob = lr.predict_proba(input_df)[0][1]
    prediction = lr.predict(input_df)[0]
    
    status = "Placed" if prediction == 1 else "Not Placed"
    print(f"\nExample Prediction for CGPA {cgpa_10_scale}:")
    print(f"  Probability of Placement: {prob:.2%}")
    print(f"  Status: {status}")

# Run an example prediction
predict_placement(8.5)